# Generated by Django 5.0.4 on 2024-05-13 18:32

import codepage.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codepage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField()),
                ("output", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="code",
            name="code_file",
            field=models.FileField(
                upload_to="", validators=[codepage.models.validate_code_file_extension]
            ),
        ),
    ]
